from fastapi.testclient import TestClient

from app.main import app
from app.schemas.github import BadgeItem, CommitItem, GitHubDashboardResponse, StageMetric, WorkflowRun
from app.schemas.jira import JiraIssueResponse
from app.services.github_service import GitHubService
from app.services.jira_service import JiraService
from app.services.llm_service import LLMService, LLMGenerationResult


def test_login_pipeline_and_refresh_with_live_jira(monkeypatch):
    def fake_generate(self, *, provider, model_name, prompt):
        return LLMGenerationResult(
            provider=provider,
            model=model_name or 'fake-model',
            raw_text='{}',
            parsed_json={
                'summary': 'Generated by test double.',
                'implementation_plan': ['Ship API', 'Ship UI'],
                'risks': ['None'],
                'acceptance_criteria': ['AC1', 'AC2'],
                'final_output': 'Ready for review.',
            },
            is_fallback=False,
        )

    monkeypatch.setattr(LLMService, 'generate_pipeline_plan', fake_generate)
    monkeypatch.setattr(GitHubService, 'fetch_repository_context', lambda self, repository, branch=None: [f'GitHub repository: {repository}'])
    monkeypatch.setattr(JiraService, 'fetch_issue', lambda self, key: JiraIssueResponse(
        key=key,
        summary='Production login hardening',
        status='In Progress',
        priority='High',
        assignee='Mahdi',
        issue_type='Story',
        project='AID',
        description='Implement secure auth, refresh tokens, and audit trail.',
        acceptance_criteria=['Secure login', 'Refresh endpoint'],
        url='https://jira.example/browse/AID-301',
    ))

    with TestClient(app) as client:
        login_response = client.post('/api/auth/login', data={'username': 'admin@example.com', 'password': 'Admin123!'})
        assert login_response.status_code == 200
        token = login_response.json()['access_token']
        assert login_response.cookies.get('refresh_token')

        refresh_response = client.post('/api/auth/refresh', cookies=login_response.cookies)
        assert refresh_response.status_code == 200
        assert refresh_response.json()['access_token']

        jira_response = client.get('/api/jira/issues/AID-301', headers={'Authorization': f'Bearer {token}'})
        assert jira_response.status_code == 200
        assert jira_response.json()['key'] == 'AID-301'

        create_response = client.post(
            '/api/pipeline/runs',
            data={
                'jira_issue_key': 'AID-301',
                'provider': 'openai',
                'github_repository': 'octocat/Hello-World',
            },
            headers={'Authorization': f'Bearer {token}'},
        )
        assert create_response.status_code == 202
        run_id = create_response.json()['run_id']

        detail_response = client.get(f'/api/pipeline/runs/{run_id}', headers={'Authorization': f'Bearer {token}'})
        body = detail_response.json()
        assert detail_response.status_code == 200
        assert body['overall_status'] == 'completed'
        assert len(body['stages']) == 4
        assert any(detail['label'] == 'Provider' for detail in body['stages'][2]['details'])


def test_github_dashboard_requires_authentication():
    with TestClient(app) as client:
        response = client.get('/api/github/dashboard?repository=octocat/Hello-World')
        assert response.status_code == 401


def test_github_dashboard_with_badges(monkeypatch):
    def fake_build_dashboard(self, repository=None, branch=None):
        return GitHubDashboardResponse(
            repository=repository or 'octocat/Hello-World',
            default_branch=branch or 'main',
            health_score=91,
            build_success_rate=95.5,
            deployments_this_week=2,
            open_issues=10,
            stars=20,
            pull_requests_open=3,
            pipeline_stages=[StageMetric(stage='Build', status='success', duration=22)],
            commits=[CommitItem(sha='1234567', message='Init', author='octocat', time='1h ago')],
            workflow_runs=[WorkflowRun(name='CI', branch='main', status='completed', conclusion='success', duration_seconds=22, started_at='2026-04-20T00:00:00Z', workflow_name='CI Pipeline', workflow_file='ci.yml')],
            badges=[BadgeItem(label='CI Pipeline', image_url='https://example.com/badge.svg', target_url='https://example.com/workflow')],
            integration_status='live',
        )

    monkeypatch.setattr(GitHubService, 'build_dashboard', fake_build_dashboard)

    with TestClient(app) as client:
        login_response = client.post('/api/auth/login', data={'username': 'admin@example.com', 'password': 'Admin123!'})
        token = login_response.json()['access_token']
        response = client.get('/api/github/dashboard?repository=octocat/Hello-World', headers={'Authorization': f'Bearer {token}'})
        assert response.status_code == 200
        payload = response.json()
        assert payload['repository'] == 'octocat/Hello-World'
        assert payload['integration_status'] == 'live'
        assert payload['badges'][0]['label'] == 'CI Pipeline'
